#!/usr/bin/env bash
# contracts/sync-abis.sh
# Automatically extracts ABIs from compiled contracts and updates frontend/src/eth/abis.ts

set -euo pipefail

echo "========================================================================"
echo "Syncing Contract ABIs to Frontend"
echo "========================================================================"
echo ""

# Check if contracts are compiled
if [ ! -d "out" ]; then
    echo "❌ Error: Contracts not compiled. Run 'forge build' first."
    exit 1
fi

# Check if required contract artifacts exist
REQUIRED_CONTRACTS=(
    "out/collectiblesRegistryV1.sol/CollectibleRegistryV1.json"
    "out/collectiblesNFTV1.sol/CollectibleNFTV1.json"
    "out/collectiblesMarketV1.sol/CollectibleMarketV1.json"
)

for contract in "${REQUIRED_CONTRACTS[@]}"; do
    if [ ! -f "$contract" ]; then
        echo "❌ Error: $contract not found. Run 'forge build' first."
        exit 1
    fi
done

echo "✅ Contract artifacts found"
echo ""

# Extract ABIs and convert to human-readable format
echo "Extracting ABIs..."

# Function to convert full ABI JSON to human-readable ethers format
function extract_human_readable_abi() {
    local contract_file=$1
    local output_var=$2
    
    # Use jq to extract function/event signatures in ethers.js human-readable format
    local abi_json=$(cat "$contract_file" | jq -r '.abi')
    
    # Convert to human-readable format (function signatures)
    local human_readable=$(echo "$abi_json" | jq -r '
        .[] | 
        select(.type == "function" or .type == "event") |
        if .type == "function" then
            "function \(.name)(" + 
            ([.inputs[] | "\(.type) \(.name)"] | join(", ")) + 
            ")" +
            (if (.outputs | length) > 0 then
                " returns (" + ([.outputs[] | .type] | join(", ")) + ")"
            else "" end) +
            (if .stateMutability == "view" or .stateMutability == "pure" then " view" else "" end)
        elif .type == "event" then
            "event \(.name)(" + 
            ([.inputs[] | (if .indexed then "indexed " else "" end) + "\(.type) \(.name)"] | join(", ")) + 
            ")"
        else "" end
    ' | sed 's/^/    "/' | sed 's/$/",/')
    
    eval "$output_var=\"\$human_readable\""
}

# Extract ABIs
extract_human_readable_abi "out/collectiblesRegistryV1.sol/CollectibleRegistryV1.json" REGISTRY_ABI
extract_human_readable_abi "out/collectiblesNFTV1.sol/CollectibleNFTV1.json" NFT_ABI
extract_human_readable_abi "out/collectiblesMarketV1.sol/CollectibleMarketV1.json" MARKET_ABI

echo "✅ ABIs extracted"
echo ""

# Generate the abis.ts file
ABIS_FILE="../frontend/src/eth/abis.ts"

echo "Generating $ABIS_FILE..."

cat > "$ABIS_FILE" << 'EOF'
// src/eth/abis.ts
// Auto-generated by contracts/sync-abis.sh
// DO NOT EDIT MANUALLY - Run ./sync-abis.sh to update

// Registry functions we call
export const REGISTRY_ABI = [
EOF

# Add Registry ABI
echo "$REGISTRY_ABI" | grep -E "(registerCollectible|transferCollectibleOwnership|redeemCollectible)" >> "$ABIS_FILE"

cat >> "$ABIS_FILE" << 'EOF'
];

// NFT (CollectibleNFTV1) ABI
export const NFT_ABI = [
EOF

# Add NFT ABI (ERC721 + custom functions)
echo "$NFT_ABI" | grep -E "(approve|getApproved|ownerOf|tokenURI|getPoints|loyaltyPoints|getTier|silverThreshold|goldThreshold|PointsAdded|AdminSetPoints|TierThresholdsUpdated)" >> "$ABIS_FILE"

cat >> "$ABIS_FILE" << 'EOF'
];

// Marketplace functions we call
export const MARKET_ABI = [
EOF

# Add Market ABI
echo "$MARKET_ABI" | grep -E "(listCollectible|cancelListing|amendListing|purchaseCollectible)" >> "$ABIS_FILE"

cat >> "$ABIS_FILE" << 'EOF'
];

// Minimal ERC20 ABI for USDC (or your mock USDC)
export const USDC_ERC20_ABI = [
    "function approve(address spender, uint256 value) returns (bool)",
    "function allowance(address owner, address spender) view returns (uint256)",
    "function balanceOf(address account) view returns (uint256)",
];
EOF

echo "✅ $ABIS_FILE generated"
echo ""

echo "========================================================================"
echo "✅ ABI Sync Complete!"
echo "========================================================================"
echo ""
echo "Updated ABIs for:"
echo "  - Registry (registerCollectible, transferCollectibleOwnership, redeemCollectible)"
echo "  - NFT (ERC721 + loyalty points)"
echo "  - Market (list, cancel, amend, purchase)"
echo ""
echo "Frontend ABIs are now in sync with deployed contracts."
echo "========================================================================"